# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
# $Header$
#

set pkg [list \
	core::harness::payment::DMBC          1.0  [list [file join payment dineromail]] \
	core::harness::payment::POLI          1.0  [list [file join payment poli]] \
	core::harness::payment::CC            1.0  [list [file join payment creditcard]] \
	core::harness::payment::SCTK          1.0  [list [file join payment safecharge_token]] \
	core::harness::video                  1.0  [list [file join video video]] \
	core::harness::api::funding_service   1.0  [list [file join api funding_service]] \
	core::harness::api::promotion_service 1.0  [list [file join api promotion_service]] \
	core::harness::api::emerchants        1.0  [list [file join api emerchants]] \
]

foreach {pkg version fs} $pkg {

	set file_list [list]

	foreach name $fs {
	
		set name [file join $dir $name]
		
		if {[file exists $name.tbc]} {
			lappend file_list $name.tbc
		} elseif {[file exists $name.tcl]} {
			lappend file_list $name.tcl
		} else {
			error "Can't load package $pkg version $version from file $name.{tbc,tcl}"
		}
	}
	
	package ifneeded $pkg $version [list foreach f $file_list {source $f}]
}
