# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
#

global admin_screens
variable TCL

set pkg_list [list \
	core::api::amqp                  1.0  [list [file join api amqp]] \
	core::api::cas_auth              1.0  [list [file join api cas_auth]] \
	core::api::core_rpc              1.0  [list [file join api core_rpc]] \
	core::api::crypto                1.0  [list [file join api crypto]] \
	core::game_history_service       1.0  [list [file join api game_history_service]] \
	core::api::qas                   1.0  [list [file join api qas]] \
	core::api::stomp                 1.0  [list [file join api stomp]] \
	core::api::rng                   1.0  [list [file join api rng]] \
	core::api::funding_service       1.0  [list [file join api funding_service]] \
	core::api::promotion_service     1.0  [list [file join api promotion_service]] \
	core::api::emerchants            1.0  [list [file join api emerchants]] \
	core::siteserver                 1.0  [list [file join api siteserver]] \
	core::verification               1.0  [list [file join api verification]] \
	\
	core::api::jenkins               1.0  [list [file join api jenkins]] \
	\
	core::cache                      1.0  [list [file join appserv cache]] \
	core::controller                 1.0  [list [file join appserv controller]] \
	core::request                    1.0  [list [file join appserv request]] \
	core::view                       1.0  [list [file join appserv view]] \
	\
	core::bet::cashout               1.0  [list [file join bet cashout]] \
	core::freebets                   1.0  [list [file join bet freebets]] \
	\
	core::cust                       1.0  [list [file join cust cust]] \
	core::cust::black_book           1.0  [list [file join cust black_book]] \
	core::cust::login                1.0  [list [file join cust login]] \
	core::cust::lost_login           1.0  [list [file join cust lost_login]] \
	core::cust::one_time_password    1.0  [list [file join cust one_time_password]] \
	core::cust::matcher              1.0  [list [file join cust matcher]] \
	core::cust::notice               1.0  [list [file join cust notice]] \
	core::cust::session              1.0  [list [file join cust session]] \
	core::cust::wallet               1.0  [list [file join cust wallet]] \
	\
	core::payment                    1.0  [list [file join payment payment]] \
	core::payment::BANK              1.0  [list [file join payment bank]] \
	core::payment::BPAY              1.0  [list [file join payment bpay]] \
	core::payment::CB                1.0  [list [file join payment clickandbuy]] \
	core::payment::CC                1.0  [list [file join payment creditcard]] \
	core::payment::DMBC              1.0  [list [file join payment dineromail]] \
	core::payment::POLI              1.0  [list [file join payment poli]] \
	core::payment::MB                1.0  [list [file join payment moneybookers]] \
	core::payment::NTLR              1.0  [list [file join payment neteller]] \
	core::payment::SCTK              1.0  [list [file join payment safecharge_token]] \
	core::payment::UKSH              1.0  [list [file join payment ukash]] \
	core::payment::CSCD              1.0  [list [file join payment cashcard]] \
	core::payment::ENET              1.0  [list [file join payment enets]] \
	core::payment::TOPC              1.0  [list [file join payment topupcard]] \
	core::payment::CSH               1.0  [list [file join payment cash]] \
	core::payment::CHQ               1.0  [list [file join payment cheque]] \
	core::payment::PPAL              1.0  [list [file join payment paypal]] \
	core::payment::PSHP              1.0  [list [file join payment paysafe_hosted]] \
	core::payment::recon_utils       1.0  [list [file join payment recon_utils]] \
	\
	core::security::aes              1.0  [list [file join security aes]] \
	core::security::gpg::agent       1.0  [list [file join security gpg_agent]] \
	core::security::gpg::simple      1.0  [list [file join security gpg_simple]] \
	core::security::passwd           1.0  [list [file join security passwd]] \
	core::security::single_use_token 1.0  [list [file join security single_use_token]] \
	core::security::token            1.0  [list [file join security token]] \
	\
	core::verification::iovation     1.0  [list [file join verification iovation]] \
	\
	core::video                      1.0  [list [file join video video]] \
	\
	core::dd                         1.0  [list [file join drilldown dd]] \
	core::dd::node                   1.0  [list [file join drilldown node]] \
	\
	core::monitor                    1.0  [list [file join monitor monitor]] \
	\
]

# Add module dependency directories
lappend ::auto_path [file join $dir db]
lappend ::auto_path [file join $dir foundation]
lappend ::auto_path [file join $dir history]
lappend ::auto_path [file join $dir slap]
lappend ::auto_path [file join $dir util]
lappend ::auto_path [file join $dir interfaces cust]
lappend ::auto_path [file join $dir interfaces funding]
lappend ::auto_path [file join $dir interfaces messaging]
lappend ::auto_path [file join $dir interfaces lottery]
lappend ::auto_path [file join $dir interfaces cust]

foreach {pkg version fs} $pkg_list {

	set file [list]

	foreach name $fs {

		set name [file join $dir $name]

		if {[file exists $name.tbc]} {
			lappend file $name.tbc
		} elseif {[file exists $name.tcl]} {
			lappend file $name.tcl
		} else {
			error "Can't load package $pkg version $version from file $name.{tbc,tcl}"
		}
	}

	set TCL($pkg,filename) $file
	set TCL($pkg,dir)      $dir
	set TCL($pkg,version)  $version

	package ifneeded $pkg $version [list source $file]
}
