# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.
#
#

global admin_screens
variable TCL

set pkg_list [list \
	core::db                         1.0  [list db] \
	core::db::failover               1.0  [list db-failover] \
	core::db::informix               1.0  [list db-informix] \
	core::db::postgreSQL             1.0  [list db-postgreSQL] \
	core::db::mySQL                  1.0  [list db-mySQL] \
	core::db::schema                 1.0  [list schema] \
	core::db::trickle                1.0  [list trickle] \
]

foreach {pkg version fs} $pkg_list {

	set file [list]

	foreach name $fs {

		set name [file join $dir $name]

		# Handle db backwards compatibility downgrade compatibility
		if {$pkg == {core::db}} {
			if {[OT_CfgGet CORE_DB_DOWNGRADE 0] || ([info exists ::core_db_downgrade] && $::core_db_downgrade)} {
				set name [file join $dir db-compat]
			}
		}

		if {[file exists $name.tbc]} {
			lappend file $name.tbc
		} elseif {[file exists $name.tcl]} {
			lappend file $name.tcl
		} else {
			error "Can't load package $pkg version $version from file $name.{tbc,tcl}"
		}
	}

	set TCL($pkg,filename) $file
	set TCL($pkg,dir)      $dir
	set TCL($pkg,version)  $version

	package ifneeded $pkg $version [list source $file]
}
